version: '3.8'

services:
  speedtest-web:
    container_name: speedtest-indo
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Uncomment if you need to persist logs or data
    # volumes:
    #   - ./logs:/app/logs
